/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arraylist;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CURLING
 */
public class AgregarCarros extends javax.swing.JFrame {

  static  ArrayList<String> carro = new ArrayList<String>();
   ImageIcon imagen1 = new ImageIcon(this.getClass().getResource("AVO1.png"));
    ImageIcon imagen2 = new ImageIcon(this.getClass().getResource("AVO2.png"));
    ImageIcon bmw = new ImageIcon(this.getClass().getResource("bmwlogo.png"));
   
   
    
    public AgregarCarros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bagregar = new javax.swing.JButton();
        tcarro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bimprimiri = new javax.swing.JButton();
        lmostrar = new javax.swing.JLabel();
        bagregar1 = new javax.swing.JButton();
        Tplaca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Tprecio = new javax.swing.JTextField();
        letiqueta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bagregar.setText("Agregar");
        bagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bagregarMouseClicked(evt);
            }
        });
        bagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagregarActionPerformed(evt);
            }
        });
        getContentPane().add(bagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 160, 250));
        getContentPane().add(tcarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 150, -1));

        jLabel1.setText("Marca");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, -1));

        bimprimiri.setText("Imprimir");
        bimprimiri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bimprimiriMouseClicked(evt);
            }
        });
        bimprimiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bimprimiriActionPerformed(evt);
            }
        });
        getContentPane().add(bimprimiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, 250));
        getContentPane().add(lmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 420, 30));

        bagregar1.setText("COMBO");
        bagregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bagregar1MouseClicked(evt);
            }
        });
        bagregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagregar1ActionPerformed(evt);
            }
        });
        getContentPane().add(bagregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 170, 250));

        Tplaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TplacaActionPerformed(evt);
            }
        });
        getContentPane().add(Tplaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 160, -1));

        jLabel2.setText("Placa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 60, 20));

        jButton1.setText("Facturacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 150, 40));

        jLabel3.setText("Precio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 50, -1));
        getContentPane().add(Tprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 170, -1));

        letiqueta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(letiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 220, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bagregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bagregarMouseClicked
        
    }//GEN-LAST:event_bagregarMouseClicked

    private void bagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagregarActionPerformed
          ClsVehiculo.setMarca(tcarro.getText());
          ClsVehiculo.setNplaca(Tplaca.getText());
           ClsVehiculo.setPrecio(Float.parseFloat(Tprecio.getText()));
           
           tcarro.setText("");
           Tprecio.setText("");
           Tplaca.setText("");
           
          
    }//GEN-LAST:event_bagregarActionPerformed

    private void bimprimiriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bimprimiriMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bimprimiriMouseClicked

    private void bimprimiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimprimiriActionPerformed

   ClsVehiculo.getNplaca(Tplaca.getText());
        
    }//GEN-LAST:event_bimprimiriActionPerformed

    private void bagregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bagregar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bagregar1MouseClicked

    private void bagregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagregar1ActionPerformed
      String cadena = new String(" Nueva linea textNMio con\n un salto de línea");
      letiqueta.setText(cadena + "\n");
    }//GEN-LAST:event_bagregar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       VentaFacturar factura = new VentaFacturar();
       factura.setSize(800,600);
       factura.setVisible(true);
       this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TplacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TplacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TplacaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    bimprimiri.setIcon(bmw);
    bagregar.setIcon(imagen1);
    bagregar1.setIcon(imagen2);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCarros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tplaca;
    private javax.swing.JTextField Tprecio;
    private javax.swing.JButton bagregar;
    private javax.swing.JButton bagregar1;
    private javax.swing.JButton bimprimiri;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel letiqueta;
    private javax.swing.JLabel lmostrar;
    private javax.swing.JTextField tcarro;
    // End of variables declaration//GEN-END:variables
}
